version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.5.0
    links:
      - dispatcher:dispatcher
    ports:
      - "80:80"
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  db:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.17.1
    links:
      - db:database
    volumes:
      - ./config/resources:/config
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "ThisIsAVeryStrongPassword!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./data/mssql:/var/opt/mssql
  request-mssql-service:
    image: semtech/mu-javascript-template
    environment:
      NODE_ENV: "development"
      DB_SERVER: "172.27.0.2"
      DB_PORT: 1433
      DB_NAME: "PoC_DB"
      DB_USER: "sa"
      DB_PASSWORD: "ThisIsAVeryStrongPassword!"
    links:
      - db:database
    volumes:
      - /home/claire/Projets/TVL/poc-request-mssql-database-service:/app/
